language: php

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-stable" CODE_COVERAGE="on"
    - php: nightly
      env: COMPOSER_FLAGS=""
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - composer analyse
  - composer cs-check
  - if [ "$CODE_COVERAGE" != 'on' ]; then composer test; fi;
  - if [ "$CODE_COVERAGE" = 'on' ]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi;

after_script:
  - if [ "$CODE_COVERAGE" = 'on' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [ "$CODE_COVERAGE" = 'on' ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
