name: Build

on:
  push:
    branches: [ "2.0" ]
  pull_request:
    branches: [ "2.0" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependencies: [lowest, highest]
        php-versions:
          - 7.4
          - 8.0
    name: PHP ${{ matrix.php-versions }} checks with ${{ matrix.dependencies }} dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-versions }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install lowest dependencies
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --prefer-lowest --prefer-dist --no-progress --no-suggest

      - name: Install highest dependencies
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --prefer-dist --no-progress --no-suggest

      - name: Run checks
        run: composer check
